title: Bad Music Hertz
email: the.sibs@badmusichertz.com
twitter_username: badmusichertz
description: Siblings celebrating and borderline obsessing over their favorite records.
baseurl: "" # The subpath of your site, e.g. /blog/
url: "https://badmusichertz.com" # The base hostname & protocol for your site
dropbox-baseurl: "https://dropbox.badmusichertz.com"
host: localhost
creator: The Barrowclift Sibs

permalink: /post/:title # Permalink posts sorted by date with directories is awful.
paginate_path: "/page/:num" # Home older/previous pages go here
paginate: 6 # Number of posts to be shown on each each paginated page.

markdown: kramdown
highlighter: rouge
show_drafts: False
future: True

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

defaults:
  - # POST SPECIFIC VARIABLES
    scope:
      path: ""      # empty string for all files
      type: "posts"   # limit to posts
    values:
      review: True # *NOT* Being viewed from home, a specific article page
      blurred-background: True # Default to showing blurred album art backdrop
      blurred-card: True # Nearly all album covers look good with the default "blurred card" theme
      dark-theme: False # Default to light theme
      share-image:  # assume a default post doesn't have an image, /images/assets/${share-image}
  - # SITE-WIDE VARIABLES
    scope:
      path: "" # all files
    values:
      anchors: True # We want sections to be anchorable by default for everything

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
