title: Bad Music Hertz
author:
  name: The Barrowclift Sibs
  email: the.sibs@badmusichertz.com
  uri: https://badmusichertz.com/about/
  twitter_handle: badmusichertz
description: Siblings celebrating and borderline obsessing over their favorite records.
baseurl: "" # The subpath of your site, e.g. /blog/
url: "https://badmusichertz.com" # The base hostname & protocol for your site
dropbox: "https://cargo.badmusichertz.com"
host: localhost
domain: badmusichertz.com

permalink: /post/:title # Permalink posts sorted by date with directories is awful.
paginate_path: "/page/:num" # Home older/previous pages go here
paginate: 12 # Number of posts to be shown on each each paginated page.

markdown: kramdown
highlighter: rouge
show_drafts: False
future: True

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

defaults:
  - # POST SPECIFIC VARIABLES
    scope:
      path: "" # match on all files
      type: "posts"
    values:
      post: True # *NOT* Being viewed from "home" (i.e. a specific article page)
      theme.article.blurred: True
      theme.card.blurred: True
      theme.article.show-menu-background: False
      theme.article.disable-dark-overlay: False
  - # SITE-WIDE VARIABLES
    scope:
      path: "" # match on all files
    values:
      anchors: True # We want sections to be anchorable by default for everything

plugins:
  - jemoji
  - jekyll-paginate
