title: Bad Music Hertz
email: "&#109;&#097;&#114;&#099;&#064;&#098;&#097;&#114;&#114;&#111;&#119;&#099;&#108;&#105;&#102;&#116;&#046;&#109;&#101;"
twitter_username: badmusichertz
description: Scrutinizing and celebrating great music one record at a time
baseurl: "" # The subpath of your site, e.g. /blog/
url: "https://badmusichertz.com" # The base hostname & protocol for your site
shelf-baseurl: "http://104.131.165.193"
host: localhost

permalink: /post/:title # Permalink posts sorted by date with directories is awful.
paginate_path: "/page/:num" # Home older/previous pages go here
paginate: 6 # Number of posts to be shown on each each paginated page.

markdown: kramdown
highlighter: rouge
show_drafts: False
future: True

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

defaults:
  - # POST SPECIFIC VARIABLES
    scope:
      path: ""      # empty string for all files
      type: "posts"   # limit to posts
    values:
      review: True # *NOT* Being viewed from home, a specific article page
      blurred-background: True # Default to showing blurred album art backdrop
      blurred-card: True # Nearly all album covers look good with the default "blurred card" theme
      dark-theme: False # Default to light theme
      share-image:  # assume a default post doesn't have an image, /images/assets/${share-image}
  - # SITE-WIDE VARIABLES
    scope:
      path: "" # all files
    values:
      anchors: True # We want sections to be anchorable by default for everything

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
